---
title: "R研究集会 #rjpusers"
---

## {{< fa bullhorn >}} お知らせ

- 2023年度の{{< fa brands r-project title='R' >}}研究集会は**2023年12月16日**（土曜日）に開催します。東京都立川市の[統計数理研究所](https://www.ism.ac.jp)での現地のほか、オンライン中継によるハイブリッド開催を企画しています。
    - 現地およびオンラインでの参加には事前登録が必要です。[こちら（別サイトに移動します）](https://rjpusers.connpass.com/event/302671/)から申込をお願いします。

### プログラム

| 時間 | 内容 | 発表者（所属） |
|:----|:----------|:-------|
| 10:00 ~ 10:05 | 開会挨拶 | 瓜生真也<br>（徳島大学） |
| 10:05 ~ 10:35 | Rで行う行列分解のいろいろ（仮） | 安川武彦<br>（株式会社JDSC） |
| 10:35 ~ 11:05 | 多変量外れ値の検出パッケージ(RMSD)について | 和田かず美<br>（総務省統計研究研修所） |
| 11:05 ~ 11:35 | Rによるバイオデータ解析(仮) | 樋口千洋<br>（医薬基盤・健康・栄養研究所/東京医科歯科大学）　|
| 11:35 ~ 12:05 | CalPoly Shiny Appsの日本語化と統計教育・アウトリーチ活動 | 川崎能典<br>（統計数理研究所） |
| 12:05 ~ 12:50 | 昼休み（45分） | |
| 12:50 ~ 13:20 | R による財務データの匿名化: NEEDS 財務データを利用した合成疑似データの生成 | 地道正行\*（関西学院大学商学部）、<br>川崎能典（統計数理研究所）、<br>阪智香（関西学院大学商学部）、<br>宮本大輔（東京大学大学院情報理工学系研究科）、<br>永田修一（関西学院大学商学部） |
| 13:20 ~ 13:50 | COVID-19関連の情報整理におけるRの利用 | 中澤港<br>（神戸大学） |
| 13:50 ~ 14:20 |　（調整中） | 谷村晋<br>（三重大学大学院医学系研究科） |
| 14:20 ~ 14:30 | | 休憩（10分） |
| 14:30 ~ 15:00 | AIと空間統計学を利用した地球環境解析 | 山川純次<br>（岡山大学学術研究院環境生命自然科学学域）　|
| 15:00 ~ 15:30 | グラフィカルモデルとLiNGAM (機械学習の数理100問シリーズ) | 鈴木讓<br>（大阪大学） |
| 15:30 ~ 16:00 | SVMによる航空機の到着順予測 | 梅崎瑞希\*（福岡女子大学）、<br>藤野友和（福岡女子大学） |
| 16:00 ~ 16:10 | | 休憩（10分） |
| 16:10 ~ 16:30 | Classification of Chubu dialects | 服部恒太<br>（徳島大学） |
| 16:30 ~ 16:55 | | LT大会 | 
| 16:55 ~ 17:00 | 閉会挨拶 | 瓜生真也<br>（徳島大学） |

連名の場合、発表者を氏名の後ろに \* を付けて示す。

## {{< fa calendar >}} 過去のイベント

下記のリンクおよびメニューバーの`最近のイベント`（直近5回分まで）から、過去のイベントのプログラムがご覧いただけます。

- [2022年度](event/2022.qmd)
- [2021年度](event/2021.qmd)
- [2020年度](event/2020.qmd)
- 2019年度は新型コロナウイルス感染症の影響により中止となりました。
- [2018年度](event/2018.qmd)
- [2017年度](event/2017.qmd)
- [2016年度](event/2016.qmd)
- [2015年度](event/2015.qmd)
- [2014年度](event/2014.qmd)
- [2013年度](event/2013.qmd)
- [2012年度](event/2012.qmd)
- [2011年度](event/2011.qmd)
- [2010年度](event/2010.qmd)
- [2009年度](event/2009.qmd)
- 2008年度
- [2007年度](event/2007.qmd)
- [2006年度](event/2006.qmd)
- [2005年度](event/2005.qmd)
