---
title: "2010年度統計数理研究所共同研究集会<br>データ解析環境Rの整備と利用"
---

- 日時: 2010年11月25日から27日
- 場所: 統計数理研究所（東京都立川市）2階　セミナー室1 (D305) ( 25日のみ　セミナー室 2 (D304) )　
- 参加費用: 無料

## プログラム

### 11月25、26日 海外ゲスト講師によるチュートリアル講演（英語）

Speakers:

- Prof. Hadley Wickham (Rice University, USA) < http://had.co.nz/ >
- Prof. Uwe Ligges, (Technische Universitat Dortmund, Germany) < http://www.statistik.tu-dortmund.de/ligges.html >

#### 25 November (Thu) 

10:30 - 17:00

| Time | Speaker | Title |
|------|:--------|:------|
| 10:30-12:00 | Hadley Wickham | Tutorial of ggplot2 (1) |
| 12:00-13:00 | | *Lunch* |
| 13:00-14:00 | Hadley Wickham | Tutorial of ggplot2 (2) |
| 14:10-15:10 | Uwe Ligges | Prospects and Challenges for CRAN - with a glance on 64-bit Windows binaries |
| 15:10-15:30 | | *Break* |
| 15:30-16:30 | Hadley Wickham | Tutorial of ggplot2 (3) |
| 16:30-17:00 | | Discussion |

#### 26 November (Fri) 

10:30 - 17:00

| Time | Speaker | Title |
|------|:--------|:------|
| 10:30-12:00 | Uwe Ligges | My first R package (1) |
| 12:00-13:00 | | *Lunch* |
| 13:00-14:00 | Uwe Ligges | My first R package (2) |
| 14:10-15:10 | Hadley Wickham | One future of interactive graphics in R |
| 15:10-15:30 | | *Break* |
| 15:30-16:30 | Uwe Ligges | My first R package (3) |
| 16:30-17:00 | | Discussion |

### 11月27日　国内ユーザによる報告（Rユーザー会）

| 時刻  | 発表者 | 演題 |
|------|:----------|:---------------|
| 09:50-10:00 | | 開会挨拶および諸連絡 |
| 10:00-10:30 | 鈴木了太（株式会社ef-prime） | Rによるデータ解析ツールの新提案 |
| 10:30-11:00 | 長島健悟（城西大学） | Rパッケージの開発・登録とメンテナンス |
| 11:00-11:30 | 青木繁伸（群馬大学） | 統計学・データ解析におけるRの活用 |
| 11:30-11:40 | 岡田昌史（筑波大学） | 『Rパッケージ本』プロジェクトのご紹介 |
| 11:40-13:00 | | *昼食* | 
| 13:00-13:30 | 村井潤一郎（文京学院大学） | 心理統計教育におけるRの利用 |
| 13:30-14:00 | 里洋平（Tokyo.R） | 地域コミュニティ「x.R」の活動とJapan.R |
| 14:00-14:30 | 牧山文彦（データキューブ株式会社） | 今更ながらのrcom/DCOM解説 |
| 14:30-15:00 | 合崎英男（農村工学研究所） | RExcelによるデータ解析 |
| 15:00-15:30 | | *休憩* |
| 15:30-16:00 | 奥村晴彦（三重大学） | TeX＋Rによる美文書・美グラフ作成 |
| 16:00-16:30 | 山本義郎（東海大学） | Rによるデータの視覚化について |
| 16:30-17:00 | 谷村晋（兵庫医科大学） | Rを用いたデータ分析における再現性の保証 |
| 17:00-17:30 | | 討論 |
