---
title: "2013年度統計数理研究所共同研究集会<br>データ解析環境Rの整備と利用"
---

- 日時: 2013年11月29日、30日
- 場所: 統計数理研究所（東京都立川市）セミナー室1
- 参加費用: 無料
- ネット中継（録画なし，ライブのみ）: http://www.ustream.tv/channel/rlangism

## プログラム

### 11月29日 海外ゲスト講師によるチュートリアル講演（英語）

Speaker: Professor Duncan Murdoch
(Department of Statistical & Actuarial Sciences,　University of Western Ontario, Canada)

| Time | Title |
|------|:------|
| 10:00-10:55 | Part I: Reproducible Research in R. Part I: using Sweave |
| 11:05-12:00 | Part II: Advanced Sweave, including patchDVI and RStudio |
| 13:00-13:55 | What's New in R 3.0.x |
| 14:05-15:00 | Beautiful tables in R: the tables package. |
| 15:10-16:05 | Writing Package Vignettes | 
| 16:05-16:20 | discussion |

#### Part I: Reproducible Research in R. Part I: using Sweave

```
Sweave is a literate programming tool for R, allowing R code to be
embedded in a LaTeX document.  When Sweave processes the document, the
code is run, and output (including graphics) is automatically embedded.
This allows documents to be produced in a way which allows readers
to reproduce all of the computations, allowing them to be better
understood and verified.   

In this talk I will give an introduction to reproducible research and
Sweave.
```

#### Part II: Advanced Sweave, including patchDVI and RStudio

```
This talk continues part I, discussing more advanced features in 
Sweave, and my patchDVI package.  The patchDVI package helps
you when developing Sweave documents.  It creates links between the
resulting .dvi or .pdf file and the Sweave source file, facilitating
editing and modification.  It also adds support for multi-file projects.
The RStudio editor implements similar functionality in an 
integrated development environment.
```

#### What's New in R 3.0.x (13:00-13:55)

```
R version 3.0.0 was released in April. In this talk I will describe the 
R release practices, and give some details about the 3.0.x series:
 - large vectors 
 - detailed parse information 
 - more flexible definition of vignettes
Plans for the future will also be discussed.
```

#### Beautiful Tables in R: the tables Package (14:05-15:00) / The tables package on CRAN

```
Tables are an old, boring topic:  everything there is to say about them was
said by Ehrenberg (JRSS A, 1977).  But they are under attack, e.g. Gelman's
tongue-in-cheek ``Why tables are really much better than graphs'' (JCGS, 2011),
because there are so many badly produced tables in published papers. The
tables package is an effort to counteract this, to make it easy to
produce good tables.  It uses a formula interface to describe the table
(reminiscent of PROC TABULATE in SAS), and produces ASCII, CSV or
LaTeX output.
```

#### Writing Package Vignettes (15:10-16:05) / The knitr package on CRAN

```
One of the best ways to write general documentation for a package
is to write a package vignette, using Sweave or another literate
programming system.  In this talk I will describe the process of 
writing vignettes, including the new additions to R that allow them
to be written for either PDF or HTML output.
```

### 11月30日 国内ユーザによる報告

中澤先生による各報告のまとめは[こちら](http://minato.sip21c.org/bulbul/20131130.html)

| 時刻  | 発表者 | 演題 |
|------|:----------|:---------------|
| 09:25-09:30 | | 開会挨拶および諸連絡 |
| 09:30-09:55 | 合崎英男（農村工学研究所） | RによるBest-Worst Scaling |
| 09:55-10:20 | 中間栄治（Com-One）・中野純司（統数研） | ハイパフォーマンスコンピューティングのためのRhpcパッケージ |
| 10:20-10:45 | 奥村晴彦（三重大） | TeX Liveと美文書第6版とR |
| 10:45-11:00 | | *休憩* |
| 11:00-11:25 | 中谷朋昭（北海道大） | 仮想状況評価法のためのパッケージDCchoice |
| 11:25-11:50 | 小池祐太・野村亮介（東京大院） | Rによる確率過程の統計解析 |
| 11:50-13:00 | | *昼食*
| 13:00-13:25 | 谷村晋（兵庫医科大） | Rによる多変量疾病地図 |
| 13:25-13:50 | 中澤港（神戸大） | 人口モデルに基づくウクライナの人口予測 |
| 13:50-14:15 | 中野康人（関西学院大） | 日刊新聞読者投稿欄の計量テキスト分析 |
| 14:15-14:30 | | *休憩* |
| 14:30-14:55 | 藤野友和（福岡女子大） | Rによるインタラクティブグラフ生成とその応用 |
| 14:55-15:20 | 鈴木了太（ef-prime） | データ解析のためのR GUIフロントエンド |
| 15:20-15:45 | 神田善伸（自治医科大） | Rコマンダーに多彩な解析メニューを追加したEZR(Easy R)の開発 |
| 15:45-16:00 | | *休憩* |
| 16:00-17:00 | | Japan.R Lightning Talk 大会:Japan.Rから5名の若手による実践報告 |
| 17:00- | | 総合討論・閉会挨拶 |
