---
title: "2018年度統計数理研究所共同研究集会<br>「データ解析環境Rの整備と利用」"
---

- 日時: 2018年12月8日（土曜日） 09:55-17:45
- 場所: 統計数理研究所（東京都立川市）セミナー室1（D305)
- 参加費用: 無料
- ネット中継（録画なし，ライブのみ）: https://youtu.be/aKzYfbkzYlc

## プログラム

| 時刻  | 発表者 | 演題 |
|------|:----------|:---------------|
| 09:55-10:00 | 中野純司・藤野友和 | 開会挨拶 |
| 10:00-10:25 | 安川武彦（日本アイ・ビー・エム株式会社） | 一般化線形モデルを起点としたデータサイエンスの実際 |
| 10:25-10:50 | 和田かず美（統計センター） | 国外の公的統計作成部局における近年の動き |
| 10:50-11:00 | | *休憩* |
| 11:00-11:25 | 鈴木了太（株式会社 ef-prime） | R AnalyticFlowによるモダンなデータ解析 |
| 11:25-11:50 | 服部恒太（徳島大学） | What students think about their universities |
| 11:50-13:00 | | *昼休み* |
| 13:00-13:25 | 江村剛志（国立中央大学、統計研究所） | compound.Cox: 単変量Cox回帰法にもとづく特徴選択（feature selection）のRパッケージ |
| 13:25-13:50 | 鈴木譲（大阪大学大学院基礎工学研究科） | Rパッケージ BNSL: 分枝限定法でベイジアンネットワークの構造学習を高速化 |
| 13:50-14:00 | | *休憩* |
| 14:00-14:25 | 岡田昌史（東京大学UMINセンター） | Rとkerasを使った臨床試験登録情報のテキスト分類 |
| 14:25-14:50 | 樋口千洋（国立研究開発法人 医薬基盤・健康・栄養研究所） | Bioconductor update / BNSL パッケージによる遺伝子ネットワーク解析 |
| 14:50-15:00 | | *休憩* |
| 15:00-15:25 | 山川純次（岡山大学大学院自然科学研究科） | RとGISによる地球環境データ解析 |
| 15:25-15:50 | 谷村晋（三重大学大学院医学系研究科） | RにおけるSimple Features Acessの実装：新しい地理空間データ構造への転換 |
| 15:50-16:00 | | *休憩* |
| 16:00-16:25 | 合崎英男（北海道大学） | パッケージsupport.BWSの改良：Case 1 Best-Worst Scaling |
| 16:25-16:50 | 地道正行（関西学院大学 商学部） | 探索的財務ビッグデータ解析 |
| 16:50-17:15 | 石田基広（徳島大学） | Rによるサーバーログ解析 |

### LTセッション

| 時刻  | 発表者 | 演題 |
|------|:----------|:---------------|
| 17:20-17:25	| 瓜生真也 | Rを用いたReproducible Researchへの挑戦 |
| 17:25-17:30 |	牧山幸史（ヤフー株式会社） | 未定 |
| 17:30-17:35 |	R の書籍や論文の執筆環境を構築する / 安部晃生（株式会社コネクトデータ）
| 17:35-17:40 |	Jia-Han Shih (Graduate Institute of Statistics, National Central University, Taiwan) | GFGM.copula: A copula-based approach for dependent competing risks analysis | 
| 17:40-17:45	| 藤野友和（福岡女子大学） | 所要時間のヒートマップを作成する |

懇親会(18:30 - 20:30)を立川駅周辺で開催します。

その他
アクセスなどは統数研のホームページをご覧ください。
近隣にはレストラン、コンビニなどはほとんどありません。昼食は立川駅などで買ってこられることをお勧めします。
