---
title: "2023年度統計数理研究所共同研究集会<br>「データ解析環境Rの整備と利用」"
---

- 日時: 2023年12月16日（土曜日） 10:00-17:20
- 場所: 統計数理研究所（Zoomによるオンライン配信併用）
- 参加費用: 無料
- ハッシュタグ: #rjpusers
- connpass: [https://rjpusers.connpass.com/event/302671/](https://rjpusers.connpass.com/event/302671/)

## プログラム

| 時間 | 演題 | 発表者（所属） |
|:----|:----------|:-------|
| 10:00 ~ 10:05 | 開会挨拶 | 瓜生真也<br>（徳島大学） |
| 10:05 ~ 10:35 | Rで行う行列分解のいろいろ | 安川武彦<br>（株式会社JDSC） |
| 10:35 ~ 11:05 | 多変量外れ値の検出パッケージRMSD及びRMSDsについて | 和田かず美<br>（総務省統計研究研修所） |
| 11:05 ~ 11:35 | Singularity仮想化でバイオデータ解析 | 樋口千洋<br>（医薬基盤・健康・栄養研究所/東京医科歯科大学）　|
| 11:35 ~ 12:05 | CalPoly Shiny Appsの日本語化と統計教育・アウトリーチ活動 | 川崎能典<br>（統計数理研究所） |
| 12:05 ~ 12:50 | 昼休み（45分） | |
| 12:50 ~ 13:20 | R による財務データの匿名化: NEEDS 財務データを利用した合成疑似データの生成 | 地道正行\*（関西学院大学商学部）、<br>川崎能典（統計数理研究所）、<br>阪智香（関西学院大学商学部）、<br>宮本大輔（東京大学大学院情報理工学系研究科）、<br>永田修一（関西学院大学商学部） |
| 13:20 ~ 13:50 | COVID-19関連の情報整理におけるRの利用 | 中澤港<br>（神戸大学） |
| 13:50 ~ 14:20 | 空間スキャン統計量を用いた疾病の地域集積性検出における近隣リストの感度分析：2021年脳梗塞死亡データによる検討 | 谷村晋<br>（三重大学大学院医学系研究科） |
| 14:20 ~ 14:30 | | 休憩（10分） |
| 14:30 ~ 15:00 | AIと空間統計学を利用した地球環境解析 | 山川純次<br>（岡山大学学術研究院環境生命自然科学学域）　|
| 15:00 ~ 15:30 | 確率的グラフィカルモデルとLiNGAM (機械学習の数理100問シリーズ) | 鈴木讓<br>（大阪大学） |
| 15:30 ~ 16:00 | SVMによる航空機の到着順予測 | 梅崎瑞希\*（福岡女子大学）、<br>藤野友和（福岡女子大学） |
| 16:00 ~ 16:10 | | 休憩（10分） |
| 16:10 ~ 16:30 | Classification of Chubu dialects | 服部恒太<br>（徳島大学） |
| 16:30 ~ 17:15 | | 総合討論 | 
| 17:15 ~ 17:20 | 閉会挨拶 | 瓜生真也<br>（徳島大学） |

連名の場合、発表者を氏名の後ろに \* を付けて示す。
