---
title: "2025年度統計数理研究所共同研究集会<br>「データ解析環境Rの整備と利用」"
---

- 日時: 2025年11月23日（日曜日） 10:15-17:20
- 場所: 統計数理研究所（Zoomによるオンライン配信併用）
- 参加費用: 無料
- ハッシュタグ: #rjpusers
- connpass: [https://rjpusers.connpass.com/event/373551/](https://rjpusers.connpass.com/event/373551/)

## プログラム

| 時間 | 内容 | 発表者（所属） |
|:----|:----------|:-------|
| 10:15 ~ 10:20 | 開会挨拶 | 瓜生真也<br>（徳島大学） |
| 10:20 ~ 10:50 | 次世代IDE、Positron入門 | 瓜生真也<br>（徳島大学） |
| 10:50 ~ 11:20 | Rによる非線形相関の評価と再現可能研究 | 鈴木了太<br>（株式会社ef-prime） | 
| 11:20 ~ 11:50 | Rでできる分布回帰のいろいろ | 安川武彦<br>（株式会社JDSC） | 
| 11:50 ~ 12:50 | 昼休み |  |
| 12:50 ~ 13:20 | グラフィカルモデルと因果探索: R言語による実装 | 鈴木 讓<br>（大阪大学 基礎工数理） | 
| 13:20 ~ 13:50 | 高校教師の動機づけに影響を与えている要因の特定 | Kota Inai （Tokushima University）<br>, Kota Hattori\* （Tokushima University） | 
| 13:50 ~ 14:20 | DuckDB + R による DataHub データの探索的財務ビッグデータ解析 | 地道正行\*（関西学院大学商学部）<br>, 宮本大輔（政策研究大学院大学政策研究科）<br>, 阪智香（関西学院大学商学部）<br>, 永田修一（関西学院大学商学部） | 
| 14:20 ~ 14:50 | MCPサーバでRを使う | 樋口千洋<br>（医薬基盤・健康・栄養研究所/東京科学大学） | 
| 14:50 ~ 15:00 | 休憩 |  |
| 15:00 ~ 15:30 | AIで加速するデータサイエンス: 活用と責任ある利用 | 瓜生真也<br>（徳島大学） |
| 15:30 ~ 16:00 | NipponMapパッケージの新機能 | 谷村晋<br>（三重大学大学院医学系研究科） |
| 16:00 ~ 16:30 | 衛星リモートセンシングデータのモデリング | 山川純次 <br>（岡山大学学術研究院環境生命自然科学学域） | 
| 16:30 ~ 17:00 | Rによる地理空間メッシュデータから行政区域代表値を算出する方法に関する検討 | 加藤遥香\*, 谷村晋<br>（三重大学大学院医学系研究科） | 
| 17:00 ~ 17:15 | 総合討論 | | 
| 17:15 ~ 17:20 | 閉会挨拶 | 瓜生真也<br>（徳島大学） |

連名の場合、発表者を氏名の後ろに \* を付けて示す。
